version: '3.8'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt/app
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
